main: catocatocato.atools.Main
name: MWeaps
version: 1
author: catocatocato
description: custom weapon maker made for UDub Minecraft by catocatocato
api-version: 1.16
commands:
  mweps:
    description: the mweps command
    usage: /mweps
    default: op
    permission: cato.mweps
